<a href="https://colab.research.google.com/github/Mahithaneural/neuralnetwork/blob/main/700756451_Mahitha_ICP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

700756451 Mahitha Gunreddy -ICP2

In [4]:
# QUE 1

class Employee:
    # DATA MEMBER TO COUNT THE NUMBER OF EMPLOYEES
    empCount = 0

    # CONSTRUCTOR TO INITIALIZE NAME, FAMILY, SALARY, DEPARTMENT
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1    # EMPLOYEE COUNT

    # FUNCTION FOR AVERAGE SALARY OF EMPLOYEE
    def avg_salary(self):
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.empCount
        print('Average salary of the Employee:', avg)

    # TO DISPLAY DETAILS OF EMPLOYEE
    def display(self):
        print('Employee Name:', self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print("==========")

# INHERITING - EMPLOYEE CLASS
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

    #FUNCTION TO DISPLAY EMPLOYEE DETAILS
    def display(self):
        print("Employee Name :", self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print('Type of Employment :', self.emp_type)
        print("==========")


# INSTANCES FOR EMPLOYEE CLASS
emp1 = Employee('Mahitha', '4', '1800000', 'Automation Tester')
# INSTANCE FOR FULL TIME EMPLOYEE
emp2 = Fulltime_Employee('Sai Kumar', '4', '1900000', 'Business Analyst', 'Fulltime')
emp3 = Fulltime_Employee('Nithya', '3', '2900000', 'Power BI Developer', 'Fulltime')

print("Count of the Employees :", emp1.empCount)
emp1.avg_salary()
emp1.display()
emp2.display()
emp3.display()

Count of the Employees : 3
Average salary of the Employee: 600000.0
Employee Name: Mahitha
Family Members: 4
Employee Annual Salary: 1800000
Department: Automation Tester
Employee Name : Sai Kumar
Family Members: 4
Employee Annual Salary: 1900000
Department: Business Analyst
Type of Employment : Fulltime
Employee Name : Nithya
Family Members: 3
Employee Annual Salary: 2900000
Department: Power BI Developer
Type of Employment : Fulltime


In [2]:
# QUE 2

import numpy as np

# creating array of size as 20
random_vector = np.random.uniform(1, 20, 20)
print("Random Vector : \n", random_vector)

# reshape the array to 4 cross 5
random_vector = random_vector.reshape(4,5)
print("after reshaping (4 by 5): \n", random_vector)

# replace the maximum in each row
random_vector[np.arange(len(random_vector)), random_vector.argmax(1)] = 0
print("Replacing the maximum in each row : \n", random_vector)

Random Vector : 
 [ 7.20959518  2.80959147 11.09229409  5.66887448  6.96125381  6.23449978
 19.46962005  2.50717153  6.04925101  1.19091294 14.84372158  2.12727097
  4.35798682 11.21499751 14.45989773 17.91441645  9.70952552 19.13302997
  8.37469704  1.95343403]
after reshaping (4 by 5): 
 [[ 7.20959518  2.80959147 11.09229409  5.66887448  6.96125381]
 [ 6.23449978 19.46962005  2.50717153  6.04925101  1.19091294]
 [14.84372158  2.12727097  4.35798682 11.21499751 14.45989773]
 [17.91441645  9.70952552 19.13302997  8.37469704  1.95343403]]
Replacing the maximum in each row : 
 [[ 7.20959518  2.80959147  0.          5.66887448  6.96125381]
 [ 6.23449978  0.          2.50717153  6.04925101  1.19091294]
 [ 0.          2.12727097  4.35798682 11.21499751 14.45989773]
 [17.91441645  9.70952552  0.          8.37469704  1.95343403]]
